name: Build and Publish Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-publish:
    uses: halkeye/halkeye/.github/workflows/build-upstream-docker.yaml@master
    secrets: inherit
    permissions:
      contents: write
      packages: write
    with:
      upstream_version: "1dfbd27cce9784a1bb7e2f85441473c1506647d6"
      upstream_repo: "https://tangled.org/tranquil.farm/tranquil-pds"
      run_number: "${{ github.run_number }}"
      username: "${{ github.repository_owner }}"
      repository: "${{ github.repository }}"
